#server:
#  port: 9002

spring:
  application:
    name: PHONE-SERVICE
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0
resilience4j:
  retry:
    instances:
      retrybasic:
        maxRetryAttemps: 5
        waitDuration: 10s
      retryAndRateLimit:
        maxRetryAttempts: 2
        waitDuration: 1s
  ratelimiter:
    instances:
      ratelimiterbasic:
        limitForPeriod: 2
        limitRefeshPeriod: 10s
        timeoutDuration: 1s
      retryAndRateLimitExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms
eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

